### PR TITLE
Improved playlists and radio messages, added method for setting repeat and shuffle

### PR DESCRIPTION
**Pull request by johanj**
-Added playlist name and repeat in Playlist message
-Added Artist to now playing radio message
-Added methods for setting playlist repeat and shuffle
-Improved starting radio channel

### CODE REVIEW

**Comment by Shukuyen** [comment]
Looks good, thanks!
Can you please update the documentation on the MediaPortal wiki when you got time? Your changes will be in API_VERSION 14. Also I can't test the radio stuff as I don't have a tv card setup at the moment.

**Comment by johanj** [comment]
Hi

Thanks for including it!

Sure, I can update the wiki further on. My first priority is to get Eve 
out.

You can test the radio stuff using webradio stations but then you need 
to install the tvserver just for that so it's probably not worth it. I 
have tested with webradio channels and Joost has tested with Tv-card 
channels.

About the new feature with screen dumps of MP. Is that just through 
WifiRemote or will it also be included in MPExtended in some way? I have 
used the WifiRemote base64 encoded images before in iViewer(we base Eve 
on this app) but it's not convenient since one has to use a javascript 
webserver to decode the image and that is kind of slow. Using the images 
that MPExtended server is really fast. It's not a feature that we have 
place for right now but it would be cool to include it further on.

Btw, the wifes usually starts to talk about having a second kid when the 
first one is about 18 months, then it starts all over again;)

Cheers,

Johan

**Comment by Shukuyen** [comment]
Hi Johan,

I don't know of any plans to integrate the screenshot feature into mpextended. Doing it the base64 way isn't perfect, I agree, but I can't think of a different way to do it in WifiRemote through the socket connections. In most languages it's also relatively simple to decode that into an image ... If you have any ideas let me know, always open for suggestions!

I won't comment on your last paragraph, sleep depreviation isn't something one should joke around with :P

**Comment by johanj** [comment]
Of course one can joke about sleep deprivation, I actually had nervous 
twitching around my eyes during the autumn. The little one sleeps better 
now so body is back to normal. A friend of mine actually got swollen 
face because of little sleep when the kid was little.

I don't have any other suggestions for encoding the image through socket 
connection, it's probably the best way if not going through MPExtended. 
But MPExtended has little to do with the MP client, it only uses it's 
databases so it's do not belong there really. Will probably test the 
feature sometime further on.

I noticed an issue with WifiRemote/MediaPortal when using screen 
blanking in MP. Starting media using WifiRemote when the screen is blank 
trigger strange things. E.g. I got a crash when starting a tv serie when 
the refresh changes kicked in. Starting playlist track throw a Last.fm 
error and so on. A workaround that works for me is to send a keystroke 
before the play command. But it should preferably be handled in 
WifiRemote. Do you have an idea of how one can handle the issue in a 
nice way in WifiRemote?

Cheers,

Johan

**Comment by Shukuyen** [comment]
Not sure I can follow what exactly the problem is (my MediaPortal setup is pretty basic, no fancy refresh rate changer stuff and the like ;)). We have something in WifiRemote to cancel the screensaver on incoming commands:
https://github.com/MPExtended/WifiRemote/blob/develop/Sources/WifiRemote/Core/SocketServer.cs#L575

For this we simulate a left-control-key press. But this isn't what you are after, right?

**Comment by johanj** [comment]
I can check the exact settings in mediaportal config this evening, but I 
think it's with gui settings. One can reduce framrate or blank screen. 
Use the blank screen setting and set the timeout to e.g. 5-10 seconds. 
Then start media through WifiRemote.

The left-control-key press should do the same as I did as workaround 
with only difference of timing of the commands and a different key. 
Maybe there need to be a longer delay between the key command and the 
play command? The workaround worked for me but not for Joost for music 
playlists, it was he that experienced the problem and I could reproduce it.

I can take a look later to see if one can turn off the screen saver in a 
better way.

Cheers,

Johan

**Comment by Shukuyen** [comment]
I opened a new issue for that bug, let's continue discussion there.

**Pull request merged**
