### PR TITLE
-Fix for previous tv channel issue

### PR DESCRIPTION
**Pull request by johanj**
Now retrieves current time-shifting tv channel from tv card instead of the navigator.

-Added TvControl.dll as dependecy.

### CODE REVIEW

**Comment by Shukuyen** [comment]
I guess it will take more than 1-2 days for me to figure out what dependencies we have :D and testing is always good.
Imho it's better to send a link to the dll via private message so we don't have different versions floating around.

**Comment by Shukuyen** [comment]
Thanks a ton!

**Comment by johanj** [comment]
Well, it's only fair that one fix the issues after introducing them:).

I sent the dll as a pm and it works for both of the persons that reported the issue.

**Comment by Shukuyen** [comment]
Ok great. I hope to find some time soon to get on that dependency system. I am back to work so that's not that easy anymore.

**Comment by johanj** [comment]
I'm afraid that I have little knowledge about how to deploy a MediaPortal plugin and no clue what the dependency system is.

**Comment by Shukuyen** [comment]
You can find some information in issue https://github.com/MPExtended/WifiRemote/issues/12
I need to collect all MediaPortal libraries/subsystems we are depending on and reference them in the AssemblyInfo.cs with the correct version.

When one of those gets updated with breaking changes in the future we need to recompile the plugin, until then it will be marked as incompatible and can't be activated. Not sure yet how to support older MediaPortal versions, probably by releasing multiple versions and compiling with conditionals ... So probably it will be best to just drop support for older versions like I did with the release for 1.6 ...

**Comment by johanj** [comment]
The simplest solution seems to be what you made fort 1.6; only support the latest version of MP. Older versions of MP can always use older versions of WifiRemote. The only drawback is that only the ones that update MP to latest version will get the new features and bugfixes of WifiRemote. 

Not sure it's worth the effort to try to support multiple versions of MP in every release. It just adds complexity in the project and you have limited time to work on this.

**Pull request merged**
